baseurl = "http://tolehico.github.io/"
languageCode = "en-us"
title = "tolehi.co"
author = "tolehico"

[params]
	facebook = "https://www.facebook.com/t.kamei"
	twitter = "https://twitter.com/tolehico"

